server:
  port: 80

spring:
  datasource:
    read:
      jdbc-url: jdbc:postgresql://database-read-replica.c7bqayif57ah.ap-northeast-2.rds.amazonaws.com/ecommerce
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver
    write:
      jdbc-url: jdbc:postgresql://database-1.c7bqayif57ah.ap-northeast-2.rds.amazonaws.com/ecommerce
      username: postgres
      password: postgres
      driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
