server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: sanho
    password: sanho0608
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

    show-sql: true
