server:
  port: 80

spring:
  datasource:
    url: jdbc:postgresql://
    username:
    password:
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:

      ddl-auto: update
    show-sql: true
