server:
  port: 80

spring:
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 3000
      maximum-pool-size: 5
      max-lifetime: 30000
      driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


cloud:
  aws:
    s3:
      bucket: prac-bucket-2023-06-28
    region:
      static: ap-northeast-2
    cloud-front:
      domain-name: https://d2r5ub9zannwe.cloudfront.net
      distribution-id: E2K0GS1TYUKKYS

